services:
  - type: web
    name: krishisaarthi-backend
    runtime: python
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        value: 579b464db66ec23bdd0000019e4dba64f69842d1547080c5536593c7
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: CORS_ORIGINS
        value: http://localhost:3000,http://127.0.0.1:3000,https://krishyak.vercel.app,https://krishisaarthi.vercel.app
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
