@echo off
echo Starting KrishiSaarthi Backend...
cd /d "%~dp0backend"
if not exist venv\Scripts\python.exe (
    echo Creating virtual environment...
    python -m venv venv
    if errorlevel 1 exit /b 1
)
echo Installing dependencies...
venv\Scripts\python.exe -m pip install -r requirements.txt
if errorlevel 1 exit /b 1
echo Starting FastAPI server...
venv\Scripts\python.exe -m uvicorn main:app --host 127.0.0.1 --port 8000
