import React from 'react';
import { FileText, ChevronLeft } from 'lucide-react';

const TermsOfService = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-farm-green-50 to-white py-8 px-4">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="flex items-center mb-8">
          {onBack && (
            <button
              onClick={onBack}
              className="mr-4 p-2 hover:bg-white rounded-lg transition-colors"
            >
              <ChevronLeft className="w-6 h-6 text-gray-600" />
            </button>
          )}
          <div className="flex items-center">
            <FileText className="w-8 h-8 text-farm-green-600 mr-3" />
            <div>
              <h1 className="text-2xl font-bold text-gray-800">Terms of Service</h1>
              <p className="text-sm text-gray-500">Last Updated: January 2026</p>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="bg-white rounded-2xl shadow-lg p-6 sm:p-8 space-y-8">
          {/* Introduction */}
          <section>
            <p className="text-gray-700 leading-relaxed">
              Welcome to Krishyak. By using this application, you agree to the following terms. 
              Please read them carefully. If you do not agree, please do not use the app.
            </p>
          </section>

          {/* Section 1 */}
          <section>
            <h2 className="text-lg font-bold text-gray-800 mb-3">1. What Krishyak Does</h2>
            <p className="text-gray-700 leading-relaxed">
              Krishyak is an <strong>AI-powered decision-support tool</strong> for Indian farmers. 
              It provides yield estimates, risk assessments, fertilizer recommendations, price forecasts, 
              scenario comparisons, government scheme matching, pest alerts, and crop disease detection. 
              All outputs are generated by machine learning models and simulation engines based on the 
              inputs you provide.
            </p>
          </section>

          {/* Section 2 */}
          <section>
            <h2 className="text-lg font-bold text-gray-800 mb-3">2. Important Disclaimers</h2>
            <div className="bg-amber-50 border-l-4 border-amber-400 rounded-r-lg p-4 space-y-3">
              <p className="text-gray-700 leading-relaxed">
                <strong>⚠️ Estimates, not guarantees.</strong> All yield predictions, profit calculations, 
                risk scores, and price forecasts are <strong>estimates based on statistical models</strong>. 
                Actual results will vary depending on weather, market conditions, pest outbreaks, and 
                many other factors beyond our control.
              </p>
              <p className="text-gray-700 leading-relaxed">
                <strong>⚠️ Not financial advice.</strong> Krishyak does not provide financial, legal, 
                or agricultural advisory services. Always consult your local Krishi Vigyan Kendra (KVK), 
                agriculture officer, or financial advisor before making major farming decisions.
              </p>
              <p className="text-gray-700 leading-relaxed">
                <strong>⚠️ Government scheme data.</strong> Scheme eligibility, benefit amounts, and 
                deadlines shown in the app are based on publicly available information and may not reflect 
                the most current rules. Always verify with the official scheme portal or your local 
                government office before applying.
              </p>
            </div>
          </section>

          {/* Section 3 */}
          <section>
            <h2 className="text-lg font-bold text-gray-800 mb-3">3. Your Responsibilities</h2>
            <ul className="list-disc list-inside space-y-2 text-gray-700">
              <li>Provide accurate farm inputs (crop, area, soil type, etc.) for meaningful results.</li>
              <li>Do not rely solely on Krishyak for critical farming or financial decisions.</li>
              <li>Keep your registration information up to date.</li>
              <li>Do not use the app for any unlawful purpose.</li>
              <li>Do not attempt to reverse-engineer, modify, or overload the app's backend services.</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section>
            <h2 className="text-lg font-bold text-gray-800 mb-3">4. Data & Privacy</h2>
            <p className="text-gray-700 leading-relaxed">
              Your data is handled according to our{' '}
              <button
                onClick={() => {
                  if (onBack) {
                    window.history.pushState({}, '', '/privacy');
                    window.dispatchEvent(new PopStateEvent('popstate'));
                  }
                }}
                className="text-farm-green-600 hover:underline font-medium"
              >
                Privacy Policy
              </button>
              . By registering, you consent to the collection and use of your data as described 
              in that document. You may withdraw consent at any time by logging out.
            </p>
          </section>

          {/* Section 5 */}
          <section>
            <h2 className="text-lg font-bold text-gray-800 mb-3">5. Disease Detection</h2>
            <p className="text-gray-700 leading-relaxed">
              The Crop Health Check feature uses AI models trained on image datasets. It can identify 
              common diseases for supported crops, but it is <strong>not a substitute for expert 
              diagnosis</strong>. If your crop shows signs of disease, also consult an agricultural 
              extension officer or plant pathologist. Misidentification is possible, especially for 
              uncommon or overlapping disease symptoms.
            </p>
          </section>

          {/* Section 6 */}
          <section>
            <h2 className="text-lg font-bold text-gray-800 mb-3">6. Service Availability</h2>
            <p className="text-gray-700 leading-relaxed">
              Krishyak requires a working internet connection for simulations, weather data, and 
              disease detection. Some features (registration data, cached results) work offline. 
              We do not guarantee uninterrupted service and may take the app offline for maintenance 
              without prior notice.
            </p>
          </section>

          {/* Section 7 */}
          <section>
            <h2 className="text-lg font-bold text-gray-800 mb-3">7. Limitation of Liability</h2>
            <p className="text-gray-700 leading-relaxed">
              To the fullest extent permitted by law, Krishyak and its developers shall not be liable 
              for any direct, indirect, incidental, or consequential damages arising from your use of 
              the app, including but not limited to crop losses, financial losses, or missed government 
              scheme deadlines.
            </p>
          </section>

          {/* Section 8 */}
          <section>
            <h2 className="text-lg font-bold text-gray-800 mb-3">8. Changes to These Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              We may update these terms from time to time. Continued use of the app after changes 
              are posted constitutes acceptance of the new terms. We will make reasonable efforts 
              to notify users of significant changes.
            </p>
          </section>

          {/* Section 9 */}
          <section>
            <h2 className="text-lg font-bold text-gray-800 mb-3">9. Contact</h2>
            <p className="text-gray-700">
              For questions about these terms, contact us at:{' '}
              <strong>support@krishyak.app</strong>
            </p>
          </section>

          {/* Footer Disclaimer */}
          <section className="bg-gray-50 rounded-xl p-4 border border-gray-200">
            <p className="text-xs text-gray-500">
              These terms are governed by and construed in accordance with the laws of India. 
              Any disputes arising from the use of Krishyak shall be subject to the exclusive 
              jurisdiction of the courts in India.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
