// Draft pilot translations; field approval is independent of code verification.
const en = {
  title: "Field Intelligence",
  subtitle: "Your fields. Your observations. Clear next steps.",
  today: "Today",
  farms: "My Farm",
  health: "Crop Health",
  market: "Market",
  benefits: "Benefits",
  planning: "Planning",
  privacy: "Privacy",
  signin: "Sign in to your farm",
  mobile: "Mobile number",
  request: "Send verification code",
  code: "Verification code",
  verify: "Verify and sign in",
  policy:
    "I agree to account processing and the Privacy Policy and Terms dated 3 October 2026.",
  unavailable:
    "Farm accounts are unavailable right now. You can continue with planning tools.",
  development:
    "Development only — synthetic test identities. Code: 123456. No SMS is sent.",
  name: "Name",
  createFarm: "Create farm",
  farmName: "Farm name",
  createPlot: "Add field",
  plotName: "Field name",
  farm: "Farm",
  area: "Manual area (hectares)",
  boundary: "Optional boundary GeoJSON",
  save: "Save",
  manual: "Manual area — boundary not mapped",
  select: "Select a field",
  empty: "Add your first farm and field to start a timeline.",
  attention: "What should I pay attention to today?",
  why: "Why am I seeing this?",
  noActions:
    "No inspection action is available. This does not establish that the field is healthy.",
  observations: "Field observations",
  note: "What did you see or do?",
  kind: "Observation type",
  record: "Record observation",
  queued: "Saved on this device. It will sync after you reconnect and sign in.",
  sync: "Sync saved observations",
  offline: "Offline — showing saved data",
  offlineOpt: "Save my fields on this device for offline use",
  offlineLimit:
    "Only downloaded fields are available offline. Satellite refresh, market updates and photo analysis need a connection.",
  latest: "Latest satellite evidence",
  refresh: "Request satellite update",
  unknown: "Not available",
  timeline: "Field timeline",
  updated: "Last saved",
  logout: "Sign out and clear this device",
  consent: "Processing permissions",
  export: "Export my account",
  delete: "Delete my account",
  deleteWarning:
    "Delete this account and its fields? This removes server records and queues photo deletion. This action cannot be undone.",
  cycle: "Crop cycle",
  crop: "Crop",
  sowing: "Sowing date",
  harvest: "Expected harvest date",
  addCycle: "Save crop cycle",
  source: "Source",
  limitations: "Limitations",
  retry: "Retry",
  loading: "Loading your fields…",
  scan: "Analyze crop photo",
  photo: "Crop photograph",
  modelScore: "Model score",
  modelLimit:
    "A classifier result needs field confirmation. It does not measure severity. Chemical treatment and dosing need local expert verification.",
  feedback: "Was this result useful or correct?",
  yes: "Yes",
  no: "No",
  unsure: "Unsure",
  drawing: "Draw field boundary",
  openMap: "Open map",
  undo: "Undo corner",
  clear: "Clear boundary",
  gps: "Zoom to my location",
  mapPrivacy:
    "Opening the map sends tile requests to the basemap service. Location is optional; manual area remains available.",
};
const hi = {
  ...en,
  title: "खेत की जानकारी",
  subtitle: "आपके खेत, आपके निरीक्षण और स्पष्ट अगले कदम।",
  today: "आज",
  farms: "मेरे खेत",
  health: "फसल स्वास्थ्य",
  market: "मंडी भाव",
  benefits: "योजनाएँ",
  planning: "योजना",
  privacy: "गोपनीयता",
  signin: "अपने खेत के खाते में प्रवेश करें",
  mobile: "मोबाइल नंबर",
  request: "सत्यापन कोड भेजें",
  code: "सत्यापन कोड",
  verify: "सत्यापित करके प्रवेश करें",
  policy:
    "मैं 3 अक्टूबर 2026 की गोपनीयता नीति और शर्तों के अनुसार खाते की जानकारी के उपयोग से सहमत हूँ।",
  unavailable:
    "खेत के खाते अभी उपलब्ध नहीं हैं। आप योजना के साधन इस्तेमाल कर सकते हैं।",
  development:
    "केवल परीक्षण — परीक्षण पहचान। कोड: 123456। कोई SMS नहीं भेजा जाता।",
  name: "नाम",
  createFarm: "फार्म बनाएँ",
  farmName: "फार्म का नाम",
  createPlot: "खेत जोड़ें",
  plotName: "खेत का नाम",
  farm: "फार्म",
  area: "दर्ज किया गया क्षेत्रफल (हेक्टेयर)",
  save: "सहेजें",
  select: "खेत चुनें",
  empty: "जानकारी दर्ज करने के लिए अपना पहला फार्म और खेत जोड़ें।",
  attention: "आज मुझे किस बात पर ध्यान देना चाहिए?",
  why: "यह क्यों दिखाया जा रहा है?",
  observations: "खेत का निरीक्षण",
  note: "आपने क्या देखा या किया?",
  kind: "निरीक्षण का प्रकार",
  record: "निरीक्षण दर्ज करें",
  queued: "इस उपकरण पर सहेजा गया। कनेक्शन और प्रवेश के बाद भेजा जाएगा।",
  sync: "सहेजे गए निरीक्षण भेजें",
  offline: "ऑफलाइन — सहेजी गई जानकारी",
  offlineOpt: "ऑफलाइन उपयोग के लिए मेरे खेत इस उपकरण पर सहेजें",
  latest: "उपग्रह की नवीनतम जानकारी",
  refresh: "उपग्रह जानकारी मँगाएँ",
  unknown: "उपलब्ध नहीं",
  timeline: "खेत का इतिहास",
  updated: "अंतिम बार सहेजा गया",
  logout: "खाते से बाहर निकलें और उपकरण की जानकारी साफ करें",
  consent: "जानकारी के उपयोग की अनुमति",
  export: "मेरे खाते की जानकारी डाउनलोड करें",
  delete: "मेरा खाता हटाएँ",
  cycle: "फसल चक्र",
  crop: "फसल",
  sowing: "बुवाई की तारीख",
  harvest: "कटाई की अनुमानित तारीख",
  addCycle: "फसल चक्र सहेजें",
  source: "स्रोत",
  limitations: "सीमाएँ",
  retry: "फिर प्रयास करें",
  loading: "खेतों की जानकारी लोड हो रही है…",
  scan: "फसल की तस्वीर जाँचें",
  photo: "फसल की तस्वीर",
  modelScore: "मॉडल स्कोर",
  feedback: "क्या यह परिणाम उपयोगी या सही था?",
  yes: "हाँ",
  no: "नहीं",
  unsure: "निश्चित नहीं",
  drawing: "खेत की सीमा बनाएँ",
  openMap: "नक्शा खोलें",
  undo: "पिछला बिंदु हटाएँ",
  clear: "सीमा साफ करें",
  gps: "मेरी जगह पर जाएँ",
};
export const farmStrings = (language) => (language === "hi" ? hi : en);
export const translationStatus = {
  en: "draft",
  hi: "draft",
  other: "english_fallback",
};
